<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>NARCFileReadingDLL</AssemblyName>
    <RootNamespace>NARCFileReadingDLL</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\NARCFileReadingDLL\*.cs" />
  </ItemGroup>
</Project>
